### ISSUE TITLE
Replace redundant creation of audio files

### ISSUE THREAD

**Issue by bun137** [acmpesuecc/attendance_shell#2]
Currently the file `take_attendance.bash` makes a `student.mp3` file for every student every time the code is run, this is redundant and can be replaced with a one time audio file creation for each student. These files can be play when taking attendance.

Your job would be to replace the redundant creation of the `student.mp3` file to a folder with all student files and play audio from them!

### Bounty points: 40

**Comment by shashidharanvs** [comment]
can i be assigned this issue

**Comment by bun137** [comment]
Hey you are assigned, you can start working on this!

**Comment by bun137** [comment]
This issue is open to contribution

**Comment by rithulkamesh** [comment]
can i get assigned

**Comment by bun137** [comment]
!assign @rithulkamesh

**Comment by bun137** [comment]
this issue has been solved!
